### ISSUE TITLE
Go forces a second network call & an additional HTTP request

### ISSUE THREAD

**Issue by jasonsalas** [TutorialEdge/go-watigroup-tutorial#1]
Really nice [demo](https://tutorialedge.net/golang/go-waitgroup-tutorial/#a-real-world-example)! It's a fantastic example of using the WaitGroup pattern with a web front-end. 

However, I noticed (both in the server's printed output and in attaching a debugger to watch the stack trace), that the code's flow apparently returns control to _handleRequests()_, which then processes the _homePage_ function and inadvertently makes a secondary network call and runs through the slice of URLs again and reruns the HTTP request and prints a second batch of response statuses. This only happens the second time and then the server sits and waits for new requests after that.

I've tried tweaking it with similar non-browser-based clients for the same WaitGroup pattern and it works as expected in those cases. I'm running Go v.1.14.3 on Windows.  Hope this helps! 

![ss](https://user-images.githubusercontent.com/1981146/86579715-06173900-bfc1-11ea-991d-4a099602fc2e.JPG)

**Comment by elliotforbes** [comment]
This is... peculiar! Let me dive in deeper to see why this happens and how I can update the example code!

**Comment by elliotforbes** [comment]
Try running a straight `curl` request against the endpoint. Opening this up in the browser would send 2 requests, one for the page and one for the `favicon.ico` which you can see in the console. This will be why it returns twice so more explicit routes would resolve this issue.

**Comment by jasonsalas** [comment]
Ha!  I was watching the network traffic in Chrome Web Inspector, and saw the page and favicon requests, but it never dawned on me that it would be forcing the additional HTTP request overall. Neat! Thanks for the help.
